---
title: Running My First R Workshop
author: 'Mara Alexeev'
date: 2021-05-25
date-modified: '`r Sys.Date()`'
categories: [R]
draft: false
description: And thoughts for making it better!
slug: running-my-first-r-workshop
image: ''
archives:
  - function () ,.Internal(date())
toc: false

format:
  html:
    code-fold: true
    code-tools: true
---

# Clinical Informatics Conference 2021

I attended the virtual Clinical Informatics Conference last week, and I also did a workshop on R for Clinical Informatics. This was the first time I had ever developed material for a workshop and run a workshop. It was a solo operation, but fortunately I had some great support from my fellowship program beforehand to get prepared. 

All the materials can be found [here](https://github.com/MaraAlexeev/R_for_Clinical_Informatics). Note the RStudio Cloud workspace has been turned off, but all the materials are available on that Github repo.

# Prior Experience

I started learning R in Spring of 2019. I started reading _R for Data Science_ and found the \#rstats twitter world. Fall of 2019 I went to my first conference about R, R/Medicine, which I now help plan! At that 2019 R/Medicine conference I went to my first workshop—[R Markdown for Medicine](https://rmd4medicine.netlify.app/), which was taught by the amazing Dr. Alison Hill.

# Planning 

I spent rough two entire work days planning the submission to CIC in January 2021. This includes all the false start ideas I had before settling on the workshop idea. This including a skeleton of some of the actual material I ended up using. 

My final submission and eventual project used simulated data that one might have while doing a Quality Improvement project to show how one could use R for the entire process or pieces of it. 

I then spent 1.5 days creating the first draft of the material in mid-April. I presented my draft to my fellowship group, got amazing feedback, and then spent another 1.5 days incorporating the feedback for that. I was able to ignore it for a few days, and then polished off the final slides that had to be submitted in a PDF format for the pre-conference materials. I then spent about another day polishing off html slides to include some nicer formatting and some ggplots, finished the materials for the attendees to do, setting everything up on RStudio Cloud, and pushing everything to a nice Github page. 

# Workshop

The workshop was held on zoom. Let me just say how thankful I am to the few people who kept their cameras on and/or who spoke. It is such wonderful feedback in the video conference isolation chamber to hear from people so you can help and adapt during the conference.

I was initially worried that the material I had and the amount was too little. I think this is unlikely to be true for me in the future! I had 100 ideas I wanted to share, but fortunately after doing a dry run with folks to my program, I was able to really trim it down to the core basics I wanted to share with some accessible extras of more advanced features. 

RStudio Cloud worked great, and no one had technical issues that they shared with me. 

One funny thing that happened as we were walking through the examples in the prepared .Rmd, is that I discussed packages and libraries, but I forgot to tell people to run that code chunk! Fortunately, someone spoke up relatively quickly and I could tell folks to do that. As an instructor, it is amazing how quickly you can forget how very not intutive the basics of coding are. 

I believe about 50 people registered for the workshop and 25 were there for any portion, and then had a solid base of 20 people for most of the workshop. 

I did a survey about people's experience with programming and R:

- About 50% of people had every programmed before in ANY language

- 40% of people had ever used R before 

- 40% had used RStudio before (presumably the same 40%?)

People's goals for the workshop ranged from seeing what R was to learning how to do specific types of plots in ggplot for their quality improvement projects. 

# Afterthoughts

I loved it. I had a great time, and I learned a ton about how to present. It was great to hear questions from folks because it forced me to give very simple, clear responses which sometimes improved my understanding. 

People asked really great questions, some of which I didn't know the answer at the time. For example, is RStudio Cloud HIPPA compliant. Answer: No! But there are other services that are that you could use R and RStudio on. 

# Do better next time

I took notes on what to do differently next time!

- Have a better way to give my contact information (on the Github page)

- Move the slides about how to knit to the point in the workshop that people will need it

- Add more real world examples of how R is or could be used in medicine

- Figure out how folks use R and RStudio in HIPAA compliant ways

- Give post-workshop tips 
  - How to download R and RStudio
  - Make a RStudio project
  - Clone a Github repo
  - Start a Github issue
  
- Show survey results 
