---
title: The Prize
author: 'Mara Alexeev'
date: 2022-10-30
date-modified: '`r Sys.Date()`'
categories: [Book Review]
draft: false
description: 'A book report, partially forgotten'
image: ''
archives:
  - function () ,.Internal(date())
toc: false

format:
  html:
    code-fold: true
    code-tools: true
---

# The Prize

I read _The Prize_ by Daniel Yergin two plus years ago while in the haze of a new baby and starting a masters and doing a fellowship, so a book report written at that time would probably be a patchy effort at best. Thus a book report written two years later is most certainly entirely suspect. However, I loved the book, and I now recommend it to anyone who will let me get to the point in a conversation where we are talking books. 

# Selected unpolished thoughts

1) how much energy enables our modern life

2) how much oil is a national security concern

3) why oil geography is wrapped up in wars

4) that the Nazis and Japanese Empire lost WWII in part because of energy insufficiency

5) how amazing the logistics of oil refinement and distribution are

6) how the needs of the oil industry created the most complicated and capable organizations in the world because they had the thing everyone wanted everywhere and there was a ton of competition

7) oil is power, figuratively 

8) maybe most people don't understand at all how important oil is because I certainly didn't before I read the book

9) how crazy the personalities were in the history of oil and how different strategies worked or did not work 

10) understanding nationalism more in the context of industrial 'imperialism'

11) importance of human capital (an oil poor country like they Netherlands is a business powerhouse because it has talented people working on them problem) and knowledge infrastructure

12) if some countries were able to get (and were not actively thwarted by external forces) themselves together they could be much better, bigger world players

13) related to that, how delicate the policies and relationships can be between companies and the country they are operating in (eg Mexico getting angry and nationalizing the oil, but if that happens then no company will ever want to go there again and then they won't be able to profit from their natural resources). Trump picking Rex Tiller as Secretary of State made much more sense after reading this book because I realized how much an Oil Company is like a country with little enclaves in many countries and assets in many (pipelines) and a non military "navy". 

14) the amazing pressure oil companies self imposed on themselves to decrease drilling and improve well conditions and the terrible conditions that were created by competing operators drilling too much into fields and causing the fields to fail prematurely because of destruction of the favorable conditions for extraction

15) the amazing technology that came out of the necessities of the oil industry

Questions I still don't understand:

1) why hydrocarbon companies aren't leading the charge into nuclear energy?

2) who benefits from the public sentiment of "big bad oil" when literally everyone in the US is using their products in many parts of their lives

3) with the oil spills that have happened, is this a lot or is this not a lot (the process sounds completely terrifying) given the complexity of the process and inherent danger in a operation of such scale with hydrocarbons and involving so many natural factors (eg the oil field, ice bergs, hurricanes)

4) why so many of the countries with this amazing resource are so poorly managed or have such repressive regimens (this is addressed but probably needs its own book!)

# Future reading

Next on my reading lists will be some of Yergin's subsequent books. I will try to do better note take for future posts.

